packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@firebase/util": false
  core-js: true
  protobufjs: false
  sharp: false
  unrs-resolver: false
overrides:
  react: 19.2.3
  react-dom: 19.2.3
